# cert-manager Helm values for production (cloud-only)
# Hardened configuration applied to Kubernetes >= 1.31 clusters.
installCRDs: true
replicaCount: 3
global:
  leaderElection:
    namespace: cert-manager
  logLevel: 2
extraArgs:
  - --cluster-resource-namespace=cert-manager
  - --enable-certificate-owner-ref=true
  - --max-concurrent-challenges=50
  - --dns01-recursive-nameservers-only
resources:
  limits:
    cpu: 750m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 384Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 2
securityContext:
  enabled: true
  fsGroup: 1001
webhook:
  replicaCount: 3
  securePort: 10250
  timeoutSeconds: 30
  hostNetwork: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9402"
    prometheus.io/path: /metrics
cainjector:
  replicaCount: 3
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
startupapicheck:
  timeout: 5m
podAnnotations:
  backup.velero.io/backup-volumes: cert-manager-data
nodeSelector:
  kubernetes.io/os: linux
  node-role.kubernetes.io/system: "true"
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cert-manager
        topologyKey: kubernetes.io/hostname
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/cert-manager-production # replace per cluster
