# cert-manager Helm values for staging (cloud-only)
# Apply to AKS/EKS/GKE staging clusters running Kubernetes >= 1.31.
installCRDs: true
replicaCount: 2
strategy: RollingUpdate
global:
  leaderElection:
    namespace: cert-manager
  logLevel: 2
extraArgs:
  - --cluster-resource-namespace=cert-manager
  - --enable-certificate-owner-ref=true
  - --controllers=*,-certificaterequests-venafi
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
securityContext:
  enabled: true
  fsGroup: 1001
webhook:
  replicaCount: 2
  securePort: 10250
  timeoutSeconds: 30
  hostNetwork: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9402"
cainjector:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
deploymentAnnotations:
  reloader.stakater.com/auto: "true"
nodeSelector:
  kubernetes.io/os: linux
tolerations: []
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cert-manager
        topologyKey: kubernetes.io/hostname
