name: Publish Dev Container

on:
  push:
    branches: [main]
    paths:
      - '.devcontainer/**'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: always
          imageTag: |
            latest
            ${{ github.sha }}

      - name: Image digest
        run: echo "Published to ghcr.io/${{ github.repository }}/devcontainer:latest"
