name: Dev Container CI

on:
  push:
    branches: [main, develop]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer-ci.yml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer:cache
          push: filter

          runCmd: |
            # Verify language runtimes installed
            echo "Verifying language runtimes..."
            dotnet --version
            go version
            python3 --version
            node --version

            # Verify Kubernetes tools installed
            echo "Verifying Kubernetes tools..."
            kind version
            kubectl version --client
            helm version
            dapr version

            # Build .NET solution
            echo "Building .NET solution..."
            dotnet restore RedDog.sln
            dotnet build RedDog.sln -c Release

            # Build UI (when it exists)
            if [ -d "RedDog.UI" ]; then
              echo "Building Vue.js UI..."
              cd RedDog.UI
              npm install
              npm run build
              cd ..
            fi

            echo "✅ All builds successful in dev container"

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            **/bin/Release/**
            RedDog.UI/dist/**
