// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using RedDog.AccountingModel;
using RedDog.AccountingModel.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AccountingContext), typeof(AccountingContextModel))]
