apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /home/ahmedmuhi/code/reddog-code/.dapr/secrets.json
