apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.state.loyalty
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
scopes:
  - loyaltyservice
